version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/simple-java
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/simple-kotlin
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - type:dependencies
