version: 2
aliases:
  - &java8_container
    image: circleci/openjdk:8
    environment:
      _JAVA_OPTIONS: -Xmx1536m
  - &java9_container
    image: circleci/openjdk:9
    environment:
      _JAVA_OPTIONS: -Xmx1536m
  - &java10_container
    image: circleci/openjdk:10
    environment:
      _JAVA_OPTIONS: -Xmx1536m
  - &checkout
    checkout:
      path: ~/orika-spring-boot-starter
  - &attach_workspace
    attach_workspace:
      at: ~/orika-spring-boot-starter-workspace
  - &restore_cache
    restore_cache:
      key: >-
        maven
        {{ .Environment.CIRCLE_JOB }}
        {{ checksum "pom.xml" }}
        {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
  - &restore_from_workspace
    run:
      name: Restoring from workspace
      command: cp -av ~/orika-spring-boot-starter-workspace/. ~
  - &build_and_test
    run:
      name: Building and testing
      command: ./mvnw -B clean install
  - &persist_to_workspace
    persist_to_workspace:
      root: "~"
      paths:
        - .m2/repository/net/rakugakibox/spring/boot/orika-spring-boot-starter
  - &save_cache
    save_cache:
      key: >-
        maven
        {{ .Environment.CIRCLE_JOB }}
        {{ checksum "pom.xml" }}
        {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
      paths:
        - ~/.m2
  - &store_test_results
    store_test_results:
      path: target/surefire-reports
  - &store_artifacts
    store_artifacts:
      path: target
      destination: /
  - &upload_codecov_reports
    run:
      name: Uploading Codecov reports
      command: curl -s https://codecov.io/bash | bash
jobs:
  ci_orika_spring_boot_starter_on_java8:
    docker:
      - *java8_container
    working_directory: ~/orika-spring-boot-starter/orika-spring-boot-starter
    steps:
      - *checkout
      - *restore_cache
      - *build_and_test
      - *persist_to_workspace
      - *save_cache
      - *store_test_results
      - *store_artifacts
      - *upload_codecov_reports
  ci_orika_spring_boot_starter_on_java9:
    docker:
      - *java9_container
    working_directory: ~/orika-spring-boot-starter/orika-spring-boot-starter
    steps:
      - *checkout
      - *restore_cache
      - *build_and_test
      - *persist_to_workspace
      - *save_cache
      - *store_test_results
      - *store_artifacts
      - *upload_codecov_reports
  ci_orika_spring_boot_starter_on_java10:
    docker:
      - *java10_container
    working_directory: ~/orika-spring-boot-starter/orika-spring-boot-starter
    steps:
      - *checkout
      - *restore_cache
      - *build_and_test
      - *persist_to_workspace
      - *save_cache
      - *store_test_results
      - *store_artifacts
      - *upload_codecov_reports
  ci_orika_spring_boot_starter_sample_on_java8:
    docker:
      - *java8_container
    working_directory: ~/orika-spring-boot-starter/orika-spring-boot-starter-sample
    steps:
      - *checkout
      - *attach_workspace
      - *restore_cache
      - *restore_from_workspace
      - *build_and_test
      - *save_cache
  ci_orika_spring_boot_starter_sample_on_java9:
    docker:
      - *java9_container
    working_directory: ~/orika-spring-boot-starter/orika-spring-boot-starter-sample
    steps:
      - *checkout
      - *attach_workspace
      - *restore_cache
      - *restore_from_workspace
      - *build_and_test
      - *save_cache
  ci_orika_spring_boot_starter_sample_on_java10:
    docker:
      - *java10_container
    working_directory: ~/orika-spring-boot-starter/orika-spring-boot-starter-sample
    steps:
      - *checkout
      - *attach_workspace
      - *restore_cache
      - *restore_from_workspace
      - *build_and_test
      - *save_cache
workflows:
  version: 2
  ci:
    jobs:
      - ci_orika_spring_boot_starter_on_java8
      - ci_orika_spring_boot_starter_on_java9
      - ci_orika_spring_boot_starter_on_java10
      - ci_orika_spring_boot_starter_sample_on_java8:
          requires:
            - ci_orika_spring_boot_starter_on_java8
      - ci_orika_spring_boot_starter_sample_on_java9:
          requires:
            - ci_orika_spring_boot_starter_on_java9
      - ci_orika_spring_boot_starter_sample_on_java10:
          requires:
            - ci_orika_spring_boot_starter_on_java10
